#!/usr/bin/python
# Project Euler Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

firstNum = 1
secondNum = 2
maxNum = 4000000
total = 2

while(firstNum + secondNum < maxNum):
    newNum = firstNum + secondNum
    if((newNum) % 2 == 0):
        total = total + newNum
    firstNum = secondNum
    secondNum = newNum

print total
# answer = 4613732
